### ISSUE TITLE
How to manually install (merge with other file)

### ISSUE THREAD

**Issue by Bluscream** [Fang86/Weapon-Mod#1]
I have a already merged my hud.lua from two other mods. How do i merge this one in without loosing the others?

**Comment by aidant86** [comment]
Oh sorry, I didn't see this. Did I help you on discord or was that someone else?

**Comment by Bluscream** [comment]
Mustve been someone else

**Comment by aidant86** [comment]
Ah ok. If you want you can send me the hud.lua file and I can make them compatible :)

**Comment by Bluscream** [comment]
Can you make this a official mod now so it doesnt replace anything?

**Comment by aidant86** [comment]
> Can you make this a official mod now so it doesnt replace anything?

I updated it yesterday so that you can just drag the "Custom Weapons" folder into the mods folder. Let me know if you still have any issues
